sudo: required
language: java
jdk: openjdk11

git:
  depth: 9999999

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

before_install:
  - chmod +x gradlew

addons:
  sonarcloud:
    organization: "joostlek-github"
    token: $SONAR_TOKEN

script:
  - TERM=dumb ./gradlew test
  - TERM=dumb ./gradlew sonarqube

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
